service: mememaker

provider:
  name: aws
  runtime: nodejs12.x

package:
  individually: true # Funcionts deploied in different terms
  excludeDevDependencies: true

exclude:
  - ./dependencies.zip
  - ./dependencies/
  - ./mock/

functions:
  mememaker:
    handler: app/handler.mememaker
    layers:
      - {ReF: GmLibraryLambdaLayer}
    events:
      - http:
          method: get
          path: mememaker
          cors: true

layers:
  GmLibrary:
    path: dependencies
    package:
      artifact: dependencies.zip
